---
- name: "Getting application eip facts..."
  ec2_eip_info:
    region: "{{ aws_region }}"
    filters:
      tag:Name: "application.project"
  register: eip_fact

- name: "Getting application ec2 facts... "
  ec2_instance_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_ec2_name_tag }}"
      "instance-state-name": "running"
  register: ec2_fact

- name: "Assigning application free eips... "
  ec2_eip:
    region: "{{ aws_region }}"
    device_id: "{{ item[0].instance_id }}"
    ip: "{{ item[1].public_ip }}"
    state: present
  loop: "{{ ec2_fact['instances']|zip(eip_fact['addresses'])|list }}"
  register: app_eip

- name: "Assigning application eips when created... "
  ec2_eip:
    region: "{{ aws_region }}"
    device_id: "{{ item.instance_id }}"
    state: present
  loop: "{{ ec2_fact['instances'] }}"
  when: eip_fact['addresses'] |list |count == 0

- name: "Setting Name tag in eips..."
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ item.allocation_id  }}"
    tags:
      Name: "application.project"
  loop: "{{ app_eip['results']|list }}"
