---
- name: "Check if server instance exist and is running... "
  ec2_instance_info:
    aws_region: "{{ aws_region }}"
    filters:
      "tag:Type": "{{ aws_ec2_type_tag }}"
      instance-state-name: running
  register: ec2_servers_state

- name: "Getting VPC id... "
  ec2_vpc_net_info:
    aws_region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: vpc
  when: ec2_servers_state['instances'] |list |count == 0

- name: "Getting vpc subnets id... "
  ec2_vpc_subnet_info:
    aws_region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0]['id'] }}"
  register: vpc_subnets
  when: ec2_servers_state['instances'] |list |count == 0

- name: "server instance creation... "
  ec2:
    aws_region: "{{ aws_region }}"
    key_name: "{{ aws_keypair }}"
    instance_type: "{{ aws_ec2_instance_type }}"
    image: "{{ aws_ec2_ami }}"
    instance_tags:
      Name: "{{ aws_ec2_name_tag }}"
      Type: "{{ aws_ec2_type_tag }}"
    count_tag:
      Name: "{{ aws_ec2_name_tag }}"
      Type: "{{ aws_ec2_type_tag }}"
    exact_count: 2
    group: ['ssh', 'web', 'icmp']
    vpc_subnet_id: "{{ vpc_subnets['subnets'][0].id }}"
    volumes:
      - device_name: xvda
        volume_type: gp2
        volume_size: "{{ aws_ec2_volume_size }}"
    wait: true
    wait_timeout: 500
    monitoring: yes
  when: ec2_servers_state['instances'] |list |count == 0
  register: ec2_servers_create
